
export const GET_TRANSLATIONS_FULFILLED = 'GET_TRANSLATIONS_FULFILLED';

export const REQUEST_UPLOAD = 'REQUEST_UPLOAD';
export const RECEIVE_UPLOAD = 'RECEIVE_UPLOAD';


export const REQUEST_ADD_PERSONNEL = 'REQUEST_ADD_PERSONNEL';
export const RECEIVE_ADD_PERSONNEL = 'RECEIVE_ADD_PERSONNEL';

export const REQUEST_PERSONNELS = 'REQUEST_PERSONNELS';
export const RECEIVE_PERSONNELS = 'RECEIVE_PERSONNELS';


export const REQUEST_ADD_PLATFORM = 'REQUEST_ADD_PLATFORM';
export const RECEIVE_ADD_PLATFORM = 'RECEIVE_ADD_PLATFORM';

export const REQUEST_PLATFORMS = 'REQUEST_PLATFORMS';
export const RECEIVE_PLATFORMS = 'RECEIVE_PLATFORMS';

export const REQUEST_ADD_PAYLOAD = 'REQUEST_ADD_PAYLOAD';
export const RECEIVE_ADD_PAYLOAD = 'RECEIVE_ADD_PAYLOAD';

export const REQUEST_PAYLOAD_TYPES = 'REQUEST_PAYLOAD_TYPES';
export const RECEIVE_PAYLOAD_TYPES = 'RECEIVE_PAYLOAD_TYPES';

export const REQUEST_PAYLOAD = 'REQUEST_PAYLOAD';
export const RECEIVE_PAYLOAD = 'RECEIVE_PAYLOAD';

export const REQUEST_PAYLOAD_DATA = 'REQUEST_PAYLOAD_DATA';
export const RECEIVE_PAYLOAD_DATA = 'RECEIVE_PAYLOAD_DATA';

export const REQUEST_ADD_MUNITION = 'REQUEST_ADD_MUNITION';
export const RECEIVE_ADD_MUNITION = 'RECEIVE_ADD_MUNITION';

export const REQUEST_MUNITION = 'REQUEST_MUNITION';
export const RECEIVE_MUNITION = 'RECEIVE_MUNITION';

export const REQUEST_ADD_LOCATION = 'REQUEST_ADD_LOCATION';
export const RECEIVE_ADD_LOCATION = 'RECEIVE_ADD_LOCATION';

export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS';
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS';

export const REQUEST_LOCATION_TYPES = 'REQUEST_LOCATION_TYPES';
export const RECEIVE_LOCATION_TYPES = 'RECEIVE_LOCATION_TYPES';

export const REQUEST_LOCATION_DATA = 'REQUEST_LOCATION_DATA';
export const RECEIVE_LOCATION_DATA = 'RECEIVE_LOCATION_DATA';


export const REQUEST_ADD_EQUIPMENT = 'REQUEST_ADD_EQUIPMENT';
export const RECEIVE_ADD_EQUIPMENT = 'RECEIVE_ADD_EQUIPMENT';

export const REQUEST_EQUIPMENTS = 'REQUEST_EQUIPMENTS';
export const RECEIVE_EQUIPMENTS = 'RECEIVE_EQUIPMENTS';


export const REQUEST_ADD_TEAM = 'REQUEST_ADD_TEAM';
export const RECEIVE_ADD_TEAM = 'RECEIVE_ADD_TEAM';

export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';


export const REQUEST_ADD_EEI = 'REQUEST_ADD_EEI';
export const RECEIVE_ADD_EEI = 'RECEIVE_ADD_EEI';

export const REQUEST_ADD_INTELREQUEST = 'REQUEST_ADD_INTELREQUEST';
export const RECEIVE_ADD_INTELREQUEST = 'RECEIVE_ADD_INTELREQUEST';

export const REQUEST_COCOM = "REQUEST_COCOM";
export const RECEIVE_COCOM = "RECEIVE_COCOM";







